export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "/Login/LoginUser",
    REGISTER: "/Login/Register",
    FORGOT_PASSWORD: "/Login/ForgotPassword",
    RESET_PASSWORD: "/Login/ResetPassword",
    CHANGE_PASSWORD: "/Login/ChangePassword",
    GET_USER_BY_ID: "/Login/GetUserById",
    UPDATE_USER: "/Login/UpdateUser",
    GET_USER_PROFILE: "/Login/GetUserProfileDetailById",
    UPDATE_USER_PROFILE: "/Login/LoginUserProfileUpdate",
    GET_LOGIN_USER_BY_ID: "/Login/LoginUserDetailById"
  },
  MISSION: {
    LIST: "/Mission/MissionList",
    DETAIL: "/Mission/MissionDetailById",
    ADD: "/Mission/AddMission",
    UPDATE: "/Mission/UpdateMission",
    DELETE: "/Mission/DeleteMission",
    THEME_LIST: "/Common/MissionThemeList",
    SKILL_LIST: "/Common/MissionSkillList",
    APPLICATION_LIST: "/Mission/MissionApplicationList",
    APPLICATION_APPROVE: "/Mission/MissionApplicationApprove",
    APPLICATION_DELETE: "/Mission/MissionApplicationDelete",
  },
  CLIENT_MISSION: {
    LIST: "/ClientMission/ClientSideMissionList",
    CLIENT_LIST: "/ClientMission/MissionClientList",
    DETAIL: "/ClientMission/MissionDetailByMissionId",
    APPLY: "/ClientMission/ApplyMission",
    ADD_COMMENT: "/ClientMission/AddMissionComment",
    COMMENT_LIST: "/ClientMission/MissionCommentListByMissionId",
    ADD_FAVORITE: "/ClientMission/AddMissionFavourite",
    REMOVE_FAVORITE: "/ClientMission/RemoveMissionFavourite",
    RATING: "/ClientMission/MissionRating",
    RECENT_VOLUNTEERS: "/ClientMission/RecentVolunteerList",
    GET_USER_LIST: "/ClientMission/GetUserList",
    SEND_INVITE: "/ClientMission/SendInviteMissionMail",
    MISSION_TITLE: "/Story/GetMissionTitle"
  },
  COMMON: {
    COUNTRY_LIST: "/Common/CountryList",
    CITY_LIST: "/Common/CityList",
    UPLOAD_IMAGE: "/Common/UploadImage",
    CONTACT_US: "/Common/ContactUs",
    ADD_USER_SKILL: "/Common/AddUserSkill",
    GET_USER_SKILL: "/Common/GetUserSkill",
    MISSION_TITLE_LIST: "/Common/MissionTitleList",
    MISSION_COUNTRY_LIST: "/Common/MissionCountryList",
    MISSION_CITY_LIST: "/Common/MissionCityList",
    MISSION_THEME_LIST: "/Common/MissionThemeList",
    MISSION_SKILL_LIST: "/Common/MissionSkillList",
  },
  TIMESHEET: {
    GET_HOURS_LIST: "/VolunteeringTimesheet/GetVolunteeringHoursList",
    GET_HOURS_BY_ID: "/VolunteeringTimesheet/GetVolunteeringHoursListById",
    ADD_HOURS: "/VolunteeringTimesheet/AddVolunteeringHours",
    UPDATE_HOURS: "/VolunteeringTimesheet/UpdateVolunteeringHours",
    DELETE_HOURS: "/VolunteeringTimesheet/DeleteVolunteeringHours",
    GET_GOALS_LIST: "/VolunteeringTimesheet/GetVolunteeringGoalsList",
    GET_GOALS_BY_ID: "/VolunteeringTimesheet/GetVolunteeringGoalsListById",
    ADD_GOALS: "/VolunteeringTimesheet/AddVolunteeringGoals",
    UPDATE_GOALS: "/VolunteeringTimesheet/UpdateVolunteeringGoals",
    DELETE_GOALS: "/VolunteeringTimesheet/DeleteVolunteeringGoals",
    VOLUNTEERING_MISSION_LIST: "/VolunteeringTimesheet/VolunteeringMissionList",
  },
  AdminUser:{
    USER_LIST: "/AdminUser/UserDetailList",
    DELETE_USER: "/AdminUser/DeleteUser",
  },
  MISSION_THEME: {
    LIST: "/MissionTheme/GetMissionThemeList",
    GET_BY_ID: "/MissionTheme/GetMissionThemeById",
    ADD: "/MissionTheme/AddMissionTheme",
    UPDATE: "/MissionTheme/UpdateMissionTheme",
    DELETE: "/MissionTheme/DeleteMissionTheme"
  },
  MISSION_SKILL: {
    LIST: "/MissionSkill/GetMissionSkillList",
    GET_BY_ID: "/MissionSkill/GetMissionSkillById",
    ADD: "/MissionSkill/AddMissionSkill",
    UPDATE: "/MissionSkill/UpdateMissionSkill",
    DELETE: "/MissionSkill/DeleteMissionSkill"
  }
}